version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
